[tool.poetry]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = ["Vladlrnv <rodilsyaletom@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg2 = "^2.9.10"
pillow = "^11.1.0"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
